import { useState } from 'react';
import Head from 'next/head'
import Link from 'next/link';
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '<test>/styles/Home.module.css'
import Nav from '<test>/components/Nav';

const inter = Inter({ subsets: ['latin'] })

import products from '../products.json';

import { useCart } from '../hooks/use-cart.js';

export default function Home() {

  const { subtotal, totalItems, addToCart, checkout } = useCart();
  
  return (
    <>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav/>

      <main className={styles.main}>

        <div>
          <h1 className={styles.title}>
            This is a test shop
          </h1>
        </div>

        <ul className={styles.grid}>
          {products.map(product => {
            const { id, title, price, description, image } = product;
            return(
              <li key={ id } className={styles.card}>
                <Link href={`/products/${id}`}>
                    <img src={ image } alt={ title }></img>
                    <h2 className={inter.className}>
                      { title }
                    </h2>
                    <h3>£{ price }</h3>
                    <p className={inter.className}>
                      { description }
                    </p>
                </Link>
                <p>
                  <button className={styles.button} onClick={() => 
                    addToCart({ 
                      id 
                    })}>Add To Cart</button>
                </p>
              </li>
            )
          })}
        </ul>
      </main>
    </>
  )
}
